name: engo
description: "engo"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.3.2+2

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  get: ^4.6.5
  shared_preferences: ^2.2.2
  path: ^1.8.3
  path_provider: ^2.1.1
  google_fonts: ^6.2.1
  audioplayers: ^6.5.0
  timelines_plus:
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  convex_bottom_bar: ^3.2.0

  floating_bottom_navigation_bar: ^1.5.2
  iconify_flutter: ^0.0.7
  colorful_iconify_flutter: ^0.0.5
  flutter_tts: ^4.2.3
  introduction_screen: ^4.0.0
  flutter_sound_button: ^0.1.1
  flutter_path_layout: ^0.1.2
  flutter_svg: ^2.0.7
  iconsax: ^0.0.8
  
 
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/sounds/
  - assets/icons/
  - assets/data/
  


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
